# Generated by Django 5.1.6 on 2025-03-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier_pdf',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
