# Generated by Django 5.1.6 on 2025-03-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parseur', '0004_alter_evaluation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveaueal',
            name='niveau',
            field=models.CharField(blank=True, choices=[('EAL2+', 'EAL2+'), ('EAL3', 'EAL3'), ('EAL4', 'EAL4')], max_length=255, null=True),
        ),
    ]
