# Generated by Django 5.1.6 on 2025-03-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_display', '0001_initial'),
        ('app_parseur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affichagedocument',
            name='evaluation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_parseur.evaluation'),
        ),
    ]
